config/routes.rb
CarListings::Application.routes.draw do
  root 'manufacturers#index'
  resources :manufacturers#, only: [:index, :new, :create, :show]
  resources :cars#, only: [:index, :new, :create]
end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :color, presence: true
  validates :year, presence: true, 
    numericality: { greater_than_or_equal_to: 1980, 
      less_than_or_equal_to: Time.now.year }
  validates :mileage, presence: true,
    numericality: { greater_than_or_equal_to: 0 }

  belongs_to :manufacturer, inverse_of: :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.order(updated_at: :desc)
  end

  def new
    @car = Car.new
    @manufacturers = Manufacturer.all.map{ |m| [m.name, m.id] }
    # @companies = Company.all.map{ |c| [c.name, c.id] }
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to new_car_path,
        notice: 'Car added!'
    else
      @manufacturers = Manufacturer.all.map{ |m| [m.name, m.id] }
      render :new
      # Couldn't get the 'Car added' to go away from the last successful add, causing tests to fail..  So did this second best option
      # redirect_to new_manufacturer_car_path(@manufacturer),
      #   notice: 'You had missing fields'
    end
  end

  private

  def car_params
    params.require(:car).permit(
      :color, :year, :mileage, :description, :manufacturer_id )
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.order(updated_at: :desc)
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    if @manufacturer.save
      redirect_to new_manufacturer_path,
        notice: 'Manufacturer added!'
      else
        render :new
      end
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h3>All the Cars</h3>

<table>
  <tr>
    <th>Color</th>
    <th>Year</th>
    <th>Mileage</th>
    <th>Description</th>
  </tr>
  
  <% @cars.each do |car| %>
    <tr>
      <td><%= car.color %></td>
      <td><%= car.year %></td> 
      <td><%= car.mileage %></td>
      <td><%= car.description %></td>
    </tr>
  <% end %>
  
</table>

<p><%= link_to 'Add Car', new_car_path %> - <%= link_to 'Add Manufacturer', new_manufacturer_path %></p>

app/views/cars/new.html.erb
<h3>Add a Car</h3>

<%= simple_form_for @car do |f| %>
  <%= f.input :manufacturer_id, collection: @manufacturers %>
  <%= f.input :color, input_html: { size: 30 } %>
  <%= f.input :year, hint: '(Must be 1980 or newer)', input_html: { size: 30 } %>
  <%= f.input :mileage, input_html: { size: 30 } %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit, 'Submit' %>
<% end %>

<p><%= link_to 'Cars Page', cars_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListings</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:notice].present? %>
    <%= flash[:notice] %>
  <% end %>
  <%= yield %>
  <%= link_to 'Home', manufacturers_path %>
</body>
</html>

app/views/manufacturers/index.html.erb
<h3>All the Manufacturers</h3>

<table>
  <tr>
    <th>Name</th>
    <th>Country of Origin</th>
  </tr>
  
  <% @manufacturers.each do |manufacturer| %>
    <tr>
      <td><%= link_to manufacturer.name, manufacturer_path(manufacturer) %></td>
      <td><%= manufacturer.country %></td> 
    </tr>
  <% end %>
  
</table>

<p><%= link_to 'Add Manufacturer', new_manufacturer_path %> - <%= link_to 'Add Car', new_car_path %></p>

app/views/manufacturers/new.html.erb
<h3>Add a Manufacturer</h3>

<%= simple_form_for @manufacturer do |f| %>
  <%= f.input :name, input_html: { size: 30 } %>  
  <%= f.input :country, collection: Manufacturer.countries %>
  <%= f.button :submit, 'Submit' %>
<% end %>

<p><%= link_to 'Manufacturers Page', manufacturers_path %></p>

app/views/manufacturers/show.html.erb
<h3><%= @manufacturer.name %></h3>

<table>
  <tr>
    <th>Company Name</th>
    <th>Country</th>
    <th>Cars Available</th>
  </tr>
  <tr>
    <td><%= @manufacturer.name %></td>
    <td><%= @manufacturer.country %></td>
    <td>
      <% @manufacturer.cars.each do |car| %>
        <li><%= "#{car.color} - #{car.year} - #{car.mileage} miles - #{car.description}"%></li>
      <% end %>
    </td>
  </tr>
</table>


<p><%= link_to 'Add a Car', new_manufacturer_car_path(@manufacturer) %></p>